Add GAH workflow to publish Doxygen
MCU-Driver-HAL/MCU-Driver-HAL pull request #11
Opened 2021-06-30 11:40 UTC by jamesbeyond

This pull-request add GHA workflows for Doxygen

- `PR-doxygen-check.yml`   checks doxygen generation on every Pull-Request 
- `PM-doxygen-publish.yml` Publish doxygen documentation on Post-Merge event

2021-06-30 12:06 UTC, jamesbeyond commented
https://github.com/MCU-Driver-HAL/MCU-Driver-HAL/pull/11

2021-06-30 20:51 UTC, fkjagodzinski requested changes

2021-06-30 20:51 UTC, fkjagodzinski commented on .github/workflows/PM-doxygen-publish.yml
> +# SPDX-License-Identifier: Apache-2.0
I'm not entirely sure, but I think we have to add the extended license header.

2021-06-30 20:51 UTC, fkjagodzinski commented on .github/workflows/PM-doxygen-publish.yml
> +          git cherry-pick --strategy=recursive --strategy-option=theirs stash@{0} -m 1
```suggestion
      # Create a commit with new html on main branch, then cherry-pick to docs-doxygen_html branch
      - name: Create a commit with new artifacts
        run: |
          MAIN_SHA=$(git rev-parse --short HEAD)
          git add ./docs/doxygen/html
          git commit -m "Doxy: Generate HTML @ $MAIN_SHA"
          git fetch origin
          git checkout origin/docs-doxygen_html
          git cherry-pick --strategy=recursive --strategy-option=theirs HEAD@{1}
```

Good to know that git-cherry-pick works with stashes :wink: but since you mentioned we want to keep this workflow in sync with the README, I think it's more appropriate to commit & cherry-pick. I think this is clearer to the reader.

Also, using git-stash has a side effect of prepending the original commit message with `On main: `.

2021-07-02 12:02 UTC, jamesbeyond commented on .github/workflows/PM-doxygen-publish.yml
> +# SPDX-License-Identifier: Apache-2.0
Why do we need the extended license header?

2021-07-02 12:16 UTC, MarceloSalazar commented on .github/workflows/PM-doxygen-publish.yml
> +# SPDX-License-Identifier: Apache-2.0
Just to be aligned with all files in the repo :)

2021-07-02 14:07 UTC, jamesbeyond commented
Updated please have a look again @fkjagodzinski

2021-07-02 14:12 UTC, fkjagodzinski approved these changes

2021-07-02 14:46 UTC, MarceloSalazar approved these changes

2021-07-06 09:36 UTC, merged