Remove the ticker event queue
MCU-Driver-HAL/MCU-Driver-HAL pull request #13
Opened 2021-07-02 08:24 UTC by fkjagodzinski

This patch removes `hal/include/hal/ticker_api.h` which used to provide a higher layer ticker API that was mostly used to handle an event queue. This is an mbed-os specific middleware.

A couple of typedefs that are needed for the us_ticker and the lp_ticker are now placed in `hal/include/hal/ticker_types.h`.

There are still some bits of dead code behind `#if MBED_CONF_USE_TICKER_EVENT_QUEUE`; I can remove these, but I think the commit history should stay unsquashed to serve as bread crumbs when integrating this repo back to the mbed-os.

2021-07-05 12:25 UTC, fkjagodzinski commented
I fixed the example named `interrupt` and gave it a more meaningful name: `us_ticker_interrupt`. I also renamed the other `us_ticker` example; it is now called `us_ticker_delay`.

This is ready for review.

2021-07-06 09:49 UTC, MarceloSalazar commented
It's looking good. Can you update `us_ticker.md` to clean-up references to events?
Perhaps we need a separate PR to update porting/testing instructions for usTicker.

2021-07-06 11:03 UTC, fkjagodzinski commented
I updated the us_ticker porting guide to be aligned with the current state of this repo. @MarceloSalazar see the latest commit.

2021-07-06 15:08 UTC, ithinuel requested changes
Only the eventqueue related method should be removed.
The following should be kept:

```c
void ticker_set_handler(const ticker_data_t *const ticker, ticker_event_handler handler);
void ticker_irq_handler(const ticker_data_t *const ticker);
us_timestamp_t ticker_read_us(const ticker_data_t *const ticker);
void ticker_suspend(const ticker_data_t *const ticker);
void ticker_resume(const ticker_data_t *const ticker);
```

2021-07-07 10:19 UTC, fkjagodzinski commented on bootstrap/mbed_wait_api_no_rtos.c
> +    const ticker_info_t *info = us_ticker_get_info();
The `ticker_read(ticker)` calls from lines 53 and 54 had to be replaced as this API has been removed. Also the while loop had to change to handle possible counter overruns; the lower layer `us_ticker_read()` does not handle overruns.

2021-07-08 09:14 UTC, ithinuel approved these changes

2021-07-08 10:20 UTC, fkjagodzinski commented
> Only the eventqueue related method should be removed.

Sorry for a misleading title/description; we're actually aiming to remove the whole `ticker` layer and leave only the `us_ticker` HAL.

2021-07-08 10:29 UTC, MarceloSalazar approved these changes

2021-07-08 10:29 UTC, merged