Closes #8: Getting started docs
MCU-Driver-HAL/MCU-Driver-HAL pull request #16
Opened 2021-07-06 17:00 UTC by Jambls

2021-07-07 09:49 UTC, MarceloSalazar commented on README.md
> +See the [Getting started guide](/docs/getting_started/README.md).
We expect more docs in the near future.
Can you please move this guide to this location: `/docs/user/README.md`, and include a section for getting started guide?

2021-07-07 09:52 UTC, MarceloSalazar commented on README.md
> +See the [Bootstrap documentation](docs/bootstrap/BOOTSRAP.md).
We should keep this file as short as possible.
Note the bootstrap doc is referenced from `/docs/README.md`

2021-07-07 09:52 UTC, MarceloSalazar commented on README.md
> +Please see [CONTRIBUTING.md](CONTRIBUTING.md) for more information.
I'm not sure why we're modifying this. It's already in the `main` branch.

2021-07-07 09:54 UTC, MarceloSalazar commented on docs/getting_started/README.md
> +Whichever compiler is chosen, it should be verified that the compiler is in the system path to allow it to be located.
Can you add a few examples on how this can be done? For example: 
`arm-none-eabi-gcc --version`
`armclang --version`

2021-07-07 09:58 UTC, MarceloSalazar commented on docs/getting_started/README.md
> +As part of the build process, make, or an equivalent build system is required. Make is usually present on Linux distributions, but another build system may need to be installed on MacOS and Windows.
```suggestion
As part of the build process, `make`, or an equivalent build system is required. `make` is usually present on Linux distributions, but another build system may need to be installed on MacOS and Windows.  [Ninja](https://ninja-build.org/) is a popular alternative.

```

2021-07-07 09:58 UTC, MarceloSalazar commented on docs/getting_started/README.md
> +In addition to the above, to run the greentea tests on device, there are some additional prerequisites.
```suggestion
In addition to the above, to run the Greentea tests on device, there are some additional prerequisites.

```

2021-07-07 10:00 UTC, MarceloSalazar commented on docs/getting_started/README.md
> +mbedhtrun is based on [Python 2.7](https://www.python.org/downloads/release/python-2716/). Pip is also required to install mbedhtrun, but it is included with all recent versions of Python 2.7.
Python 2.x is deprecated. We should recommend Python 3.x.
@jamesbeyond you may want to suggest a specific version that will be used for testing?

2021-07-07 10:01 UTC, MarceloSalazar commented on docs/getting_started/README.md
> +This is required to run the greentea tests. Once you have Python installed, it can be installed with pip with this command:
```suggestion
This is required to run the Greentea tests. Once you have Python installed, it can be installed with pip with this command:

```

2021-07-07 10:02 UTC, MarceloSalazar commented on docs/getting_started/README.md
> +See the [HAL porting guide](docs/porting/PORTING.md) for help with supporting new targets.
IMO we should try to reduce the number of links, as updating them will be a pain...
Perhaps point to an existing readme file for general info about docs? --> `/docs/README.md`

2021-07-07 10:09 UTC, jamesbeyond commented on docs/getting_started/README.md
> +mbedhtrun is based on [Python 2.7](https://www.python.org/downloads/release/python-2716/). Pip is also required to install mbedhtrun, but it is included with all recent versions of Python 2.7.
mbedhtrun support both python2.7 and python3.[6-9], https://pypi.org/project/mbed-host-tests/
we recommend Python 3.x, also didn't drop the backward compatible with python2.7

2021-07-07 11:16 UTC, Jambls commented on README.md
> +Please see [CONTRIBUTING.md](CONTRIBUTING.md) for more information.
This was moved, well, other stuff was moved, but git thinks it was just this.

2021-07-07 13:36 UTC, Jambls commented
Made the suggested changes and tidied up.

2021-07-07 14:56 UTC, MarceloSalazar commented on docs/user/README.md
> +The latest version of [Cmake](https://cmake.org/download/) is required for the build process.
```suggestion
Use [Cmake](https://cmake.org/download/) v3.19.0 or newer for the build process.
```

2021-07-07 15:01 UTC, MarceloSalazar commented on docs/user/README.md
> +### mbed-host-tests
```suggestion
### mbedhtrun
```

2021-07-07 15:04 UTC, MarceloSalazar commented on docs/user/README.md
> +mbed-host-tests is based on [Python](https://www.python.org/downloads/). Pip is also required to install mbed-host-tests, but it is included with all recent versions of Python.
```suggestion
[Python](https://www.python.org/downloads/) v3.8+ is recommended. Pip (included with all recent versions of Python) is required to install packages.

```

2021-07-07 15:06 UTC, MarceloSalazar commented on docs/user/README.md
> +This is required to run the Greentea tests. Once you have Python installed, it can be installed with pip with this command:
```suggestion
This tool is part of the [mbed-host-tests](https://pypi.org/project/mbed-host-tests/) Pip package and is required to run the Greentea tests. Once you have Python installed, it can be installed with pip with this command:

```

2021-07-07 15:07 UTC, MarceloSalazar commented on docs/user/README.md
> +It should be verified that mbedhtrun is in the system path. This can be done by running `mbedhtrun --version`.
```suggestion
It should be verified that `mbedhtrun` is in the system path. This can be done by running `mbedhtrun --version`.

```

2021-07-07 15:08 UTC, MarceloSalazar commented
@Jambls thanks for the fixes - it's looking good. I've made a few suggestions on tools and versions.

2021-07-07 15:09 UTC, Jambls commented
I have accepted the suggestions.

2021-07-07 16:16 UTC, Gallagator approved these changes
Everything looks good. I like that everything is clear and concise.

2021-07-08 14:17 UTC, MarceloSalazar submitted a review, later dismissed

2021-07-08 14:20 UTC, MarceloSalazar commented
@Jambls please rebase and resolve conflicts. We'll merge soon after that.

2021-07-08 15:47 UTC, MarceloSalazar commented on README.md
> -
These lines shouldn't be removed.

2021-07-08 15:49 UTC, MarceloSalazar commented on README.md
> -
This shouldn't be removed

2021-07-08 15:50 UTC, MarceloSalazar requested changes
Please restore missing items about Licence

2021-07-08 16:06 UTC, Jambls commented
Even though it looks like one of those is still being removed, it's also being added back in.

2021-07-08 16:43 UTC, MarceloSalazar approved these changes

2021-07-08 16:44 UTC, merged

2021-07-08 17:22 UTC, Gallagator commented on docs/user/README.md
> +$ pip3 install mbed-host-tests --upgrade
This works fine on a fresh linux mint installation as well as on my debian machine. Though, I did have to change update my PATH variable on linux mint in order to run this. I think this is more of a problem with pip/mint rather than the command itself.

2021-07-08 17:26 UTC, MarceloSalazar commented on docs/user/README.md
> +$ pip3 install mbed-host-tests --upgrade
Thanks Liam for checking!