Support FPGA CI Test Shield
MCU-Driver-HAL/MCU-Driver-HAL pull request #32
Opened 2021-07-13 08:30 UTC by fkjagodzinski

- Bring `tools/COMPONENT_FPGA_CI_TEST_SHIELD` from mbed-os @ 6.11.
- Enable `tests/mbed_hal_fpga_ci_test_shield/gpio`.
- Enable `tests/mbed_hal_fpga_ci_test_shield/gpio_irq`.
- A couple of updates to make this all work:
    - Update CMake files.
    - Disable all the _FPGA CI Test Shield_ features related to firmware handling (e.g. firmware update) with `TESTER_USE_FW_UPDATE_FEATURE` macro. These depend on mbed-os' `FileHandle` and `Callback`.
    - Bring `DigitalInOut` class from mbed-os @ 6.11 and make it part of `tools/COMPONENT_FPGA_CI_TEST_SHIELD`.
    - Disable support for all peripherals except GPIO in `tools/COMPONENT_FPGA_CI_TEST_SHIELD/include/fpga_ci_test_shield/test_utils.h`. This should be reverted/fixed when enabling more test-shield tests.
    - Bring `tools/cxxsupport` from mbed-os @ 6.11.
    - Bring some of the sources back to build (e.g. `source/mbed_compat.c`, `source/mbed_pinmap_default.cpp`).
    - Use the custom IO greentea-client feature in test-shield tests.

2021-07-13 08:31 UTC, fkjagodzinski commented
This fixes #24 after the updates to `main` branch.

2021-07-13 09:04 UTC, fkjagodzinski commented
We already had a bit of discussion in the old PR. Here is the most relevant part https://github.com/MCU-Driver-HAL/MCU-Driver-HAL/pull/24#issuecomment-878204713:

> > The CMake name of the FPGA CI Test Shield lib, mbed-fpga-ci-test-shield -- do we keep that/do we rename now/do we rename as a part of bigger overhaul?
> 
> Keep it for now- we'll handle a rename later, as it impacts many drivers/files.
> 
> > The dir name tools/COMPONENT_FPGA_CI_TEST_SHIELD looks weird in this repo; we tend to use lower case -- shall I rename this to something like tools/fpga_ci_test_shield?
> 
> Yes please, but again, can be done later if it impacts many drivers/files.
> 
> > Is the tools/cxxsupport the right location for cxxsupport mbed-core feature?
> 
> IMO it's not the ideal place, but we need a restructure of files/folders anyway (see tools, bootstrap, hal/utils)
> I'd suggest we keep this here for now. @hugueskamba feel free to chime in
> 
> > Can we keep hal/source/mbed_pinmap_default.cpp in it's current location? Should I move that to tools/COMPONENT_FPGA_CI_TEST_SHIELD?
> 
> This seems needed regardless on whether there is a FPGA CI test shield or not.
> I'd suggest we rename it to `.c` as doesn't seem C++ code.
> 
> > Do we change the old-school SPI master/slave names already or shall this part wait for being actually used by the tests (when these get enabled)?
> 
> We should be able to change comments / docs as needed. However API needs to remain a bit more, so we don't break backwards compatibility. We'll address this as part of HAL API evolution.

2021-07-13 16:08 UTC, MarceloSalazar commented on tools/COMPONENT_FPGA_CI_TEST_SHIELD/CMakeLists.txt
> +# Copyright (c) 2020 ARM Limited. All rights reserved.
Please update header with new year

2021-07-13 16:08 UTC, MarceloSalazar commented on tools/COMPONENT_FPGA_CI_TEST_SHIELD/include/fpga_ci_test_shield/DigitalInOut.h
> +/* mbed Microcontroller Library
Please update header with new year and license

2021-07-13 16:09 UTC, MarceloSalazar commented on tools/COMPONENT_FPGA_CI_TEST_SHIELD/include/fpga_ci_test_shield/DynamicPinList.h
> +/*
Please update header with new year and license

2021-07-13 16:09 UTC, MarceloSalazar commented on tools/COMPONENT_FPGA_CI_TEST_SHIELD/include/fpga_ci_test_shield/I2CTester.h
> +/*
Please update header with new year and license

2021-07-13 16:10 UTC, MarceloSalazar commented on tools/COMPONENT_FPGA_CI_TEST_SHIELD/include/fpga_ci_test_shield/MbedTester.h
> +/*
Please update header with new year and license

2021-07-13 16:10 UTC, MarceloSalazar commented on tools/COMPONENT_FPGA_CI_TEST_SHIELD/include/fpga_ci_test_shield/SPIMasterTester.h
> +/*
Please update header with new year and license

2021-07-13 16:10 UTC, MarceloSalazar commented on tools/COMPONENT_FPGA_CI_TEST_SHIELD/include/fpga_ci_test_shield/SPISlaveTester.h
> +/*
Please update header with new year and license

2021-07-13 16:11 UTC, MarceloSalazar commented on tools/COMPONENT_FPGA_CI_TEST_SHIELD/include/fpga_ci_test_shield/SPITester.h
> +/*
Please update header with new year and license

2021-07-14 12:42 UTC, fkjagodzinski commented
A couple of updates:

- Got rid of `tools/cxxsupport` (previously brought from mbed-os @ 6.11.) and disabled the C++ templates for atomic operations with a `USE_MBED_ATOMIC_TEMPLATES` macro. These templates require `mstd::type_identity` provided by the `mstd_type_traits` header. The standard `type_traits` is missing this feature for `cxx_std_14`. There is an alternative -- changing https://github.com/MCU-Driver-HAL/MCU-Driver-HAL/blob/c6950a8d16a64f0f4cc874199609cda7eec19d0e/CMakeLists.txt#L99 to `cxx_std_20`. Any votes on going this way?
- Renamed `tools/COMPONENT_FPGA_CI_TEST_SHIELD` to `tools/fpga_ci_test_shield`.
- Updated all license headers in `tools/fpga_ci_test_shield`.

2021-07-15 07:48 UTC, ithinuel requested changes

2021-07-15 07:48 UTC, ithinuel commented on CMakeLists.txt
> +if (BUILD_GREENTEA_TESTS)
This changes the work flow and requires an extra argument to be passed to `cmake`.
Can we not have this for now or update the relevant documents?

2021-07-15 07:48 UTC, ithinuel commented on tools/fpga_ci_test_shield/include/fpga_ci_test_shield/DigitalInOut.h
> +/* Copyright (c) 2006-2021 Arm Limited
This class is pretty shallow and does not seem to be inherited anywhere.
Shall we take this opportunity **not** to add it and update the mbed tester to rely on gpio_api instead?

2021-07-15 07:48 UTC, ithinuel commented on hal/source/mbed_gpio_irq.c
> +#include "bootstrap/mbed_toolchain.h"
Is there a reason for having some include split in and out of the guarded region?
If not, can be keep them packed together (either in or out)?

2021-07-15 07:48 UTC, ithinuel commented on tests/mbed_hal_fpga_ci_test_shield/gpio/main.cpp
> +#include "./gpio_fpga_test.h"
why do we have a relative include path here?

2021-07-15 07:48 UTC, ithinuel commented on tests/mbed_hal_fpga_ci_test_shield/gpio_irq/main.cpp
> +#include "hal/gpio_api.h"
This breaks the alphabetical ordering of the includes.

2021-07-15 07:48 UTC, ithinuel commented on tools/fpga_ci_test_shield/CMakeLists.txt
> +        include/fpga_ci_test_shield
We should not add that line to enforce the benefit of using include path as namespaces.

2021-07-15 08:24 UTC, MarceloSalazar commented on CMakeLists.txt
> +if (BUILD_GREENTEA_TESTS)
Can we define this at the top level application/test's cmake configuration?
Some libraries may need to be compiled differently depending on this flag.

2021-07-15 11:50 UTC, fkjagodzinski commented on CMakeLists.txt
> +if (BUILD_GREENTEA_TESTS)
> or update the relevant documents?

Already done for ST in a pending PR https://github.com/MCU-Driver-HAL/MCU-Driver-ST/pull/15/commits/9bc4df16d3998e394c401005507776d492a8ac10.

I think the main cause for adding this arg was that the previous version of this change set added the `cxxsupport` that extended the `mbed-core` CMake target.

The above is no longer true but I still like the separation the arg adds to HAL and greentea tests. I'm fine with either keeping it or removing?

@MarceloSalazar keep / remove / update?

2021-07-15 11:59 UTC, fkjagodzinski commented on hal/source/mbed_gpio_irq.c
> +#include "bootstrap/mbed_toolchain.h"
Done https://github.com/MCU-Driver-HAL/MCU-Driver-HAL/pull/32/commits/c26369525f2218d55e4d16568a9468363fb5c0a4

2021-07-15 12:10 UTC, fkjagodzinski commented on tests/mbed_hal_fpga_ci_test_shield/gpio/main.cpp
> +#include "./gpio_fpga_test.h"
Oh, this is just an effect of me really getting to like the ordered headers list. The effect I really like is that related headers are grouped (by dir prefix). I wanted to have that feature also for the closest ones. Of course this might make more sense when we have more headers in `./`.
Anyway, do we want to introduce such convention or shall I change that to `#include "gpio_fpga_test.h"`

2021-07-15 12:29 UTC, fkjagodzinski commented on tools/fpga_ci_test_shield/CMakeLists.txt
> +        include/fpga_ci_test_shield
Done c92bd5d8bf4f125bec977f7dc63317e84d00248a

2021-07-15 12:31 UTC, fkjagodzinski commented on tools/fpga_ci_test_shield/include/fpga_ci_test_shield/DigitalInOut.h
> +/* Copyright (c) 2006-2021 Arm Limited
This still requires non-zero effort on updating the `MbedTester`. Will look into this.

2021-07-15 13:04 UTC, fkjagodzinski commented
Latest updates:

- Changed `hal/source/mbed_pinmap_default.cpp` to `.c` and added changes required to fix `error: initializer element is not constant` (C vs C++ difference).
- Fixed a couple of issues with `#include` directives.
- Renamed the macros I previously added to disable some features -- added a common prefix:
    - `EXTRA_DEPENDENCIES_REQUIRED__ATOMIC_TEMPLATES`,
    - `EXTRA_DEPENDENCIES_REQUIRED__MBEDTESTER_FW_UPDATE`.

I'll now work on removing `DigitalInOut` class. Apart from that, this is read to be re-reviewed.

2021-07-15 13:39 UTC, MarceloSalazar commented on tests/mbed_hal_fpga_ci_test_shield/gpio/main.cpp
> +#include "./gpio_fpga_test.h"
I'd suggest we keep consistency.
I haven't seen relative paths elsewhere, so I'd propose we use `#include "gpio_fpga_test.h"` if that's ok?

2021-07-15 13:43 UTC, MarceloSalazar commented on CMakeLists.txt
> +if (BUILD_GREENTEA_TESTS)
I'd prefer us to reduce the number of arguments and have consistency on how we compile apps / tests.
If we're compiling a test, the top level config should identify that that pass the flag accordingly, but don't know if that's possible. This should help us to compile all cmake projects from root dir

@ithinuel please review and share your thoughts

2021-07-15 13:49 UTC, ithinuel commented on tests/mbed_hal_fpga_ci_test_shield/gpio/main.cpp
> +#include "./gpio_fpga_test.h"
This is just an opinion but I tend to prefer absolute path to serve as fully qualified namespaces for headers.
This proved to me more reliable and less error prone than relative path with possibly colliding file names.
This also simplifies the definition of include path with just the root of the module/project.

2021-07-15 13:52 UTC, ithinuel commented on CMakeLists.txt
> +if (BUILD_GREENTEA_TESTS)
the greentea tests and the hal are already nicely separated (in different cmake libraries) so this adds more complexity than effectively required.

2021-07-15 13:56 UTC, ithinuel commented on tools/fpga_ci_test_shield/include/fpga_ci_test_shield/DigitalInOut.h
> +/* Copyright (c) 2006-2021 Arm Limited
Yes, It was not a definitive request, but rather a question for @MarceloSalazar 's opinion.

2021-07-15 13:58 UTC, ithinuel commented on CMakeLists.txt
> +if (BUILD_GREENTEA_TESTS)
I vote for **not** having this flag!

2021-07-15 14:05 UTC, fkjagodzinski commented on CMakeLists.txt
> +if (BUILD_GREENTEA_TESTS)
All clear! I'll remove it.

2021-07-15 14:06 UTC, MarceloSalazar commented on CMakeLists.txt
> +if (BUILD_GREENTEA_TESTS)
I agree - we probably don't want to include code/libs that we don't need.
I assume we compile everything and the linker will remove what's not needed?
Do you have other solution in mind?

2021-07-15 14:06 UTC, ithinuel commented on hal/CMakeLists.txt
> +        source/mbed_pinmap_default.cpp
Thinking about it, those rely heavily on `weak` symbols and I would love so see them annihilated.
We could get rid of `MBED_WEAK` in there and gate those function with an `#ifndef CONFIG_NO_DEFAULT_PINMAP` when a target wants to define its own pinmap.

OTOH this kind of softly break the promise of backward compat with Mbed-OS 6.11 compat'.
It is still compatible but requires an extraflag but we already break that promise by using cmake rather than `mbed-cli` so 🤷 .

@MarceloSalazar thoughts?

2021-07-15 14:59 UTC, fkjagodzinski commented on tests/mbed_hal_fpga_ci_test_shield/gpio/main.cpp
> +#include "./gpio_fpga_test.h"
Fixed via ac1cbae & 544ac39.

2021-07-15 15:03 UTC, MarceloSalazar commented on tools/fpga_ci_test_shield/include/fpga_ci_test_shield/DigitalInOut.h
> +/* Copyright (c) 2006-2021 Arm Limited
I see there are more files / peripherals that would require an update to be consistent, hence I don't think we should do this right now. Let's enable tests and work on a clean up soon.

2021-07-15 15:06 UTC, MarceloSalazar commented on hal/CMakeLists.txt
> +        source/mbed_pinmap_default.cpp
This is something that has been identified as dependency  and the need to clean/fix, but not at the moment (requires an update of all MCU-Driver-HAL)

2021-07-15 15:08 UTC, MarceloSalazar commented
@fkjagodzinski let us know when the PR is ready for re-review

2021-07-15 15:13 UTC, fkjagodzinski commented on CMakeLists.txt
> +if (BUILD_GREENTEA_TESTS)
Done, 2e481b1

2021-07-15 15:16 UTC, fkjagodzinski commented
> @fkjagodzinski let us know when the PR is ready for re-review

It is now! :smiley: 

I'll clean up/squash the commit history once this is accepted. This will also remove the commit that didn't pass the DCO check.

2021-07-15 15:37 UTC, MarceloSalazar approved these changes

2021-07-15 16:38 UTC, ithinuel commented on hal/source/mbed_pinmap_default.c
> +    .peripheral = restricted_uart_peripherals
Does this pointer hast to be valid if `count = 0`?
It seems fair to me to have a NULL pointer there and simplify the code :)

2021-07-15 16:42 UTC, ithinuel reviewed
~Almost there :D Last one is more a question/comment than a request for changes.~

A nice squash/rebase into a few sensible commits and we'll be ready to merge 🎉

2021-07-15 16:42 UTC, ithinuel commented on hal/source/mbed_pinmap_default.c
> +    .peripheral = restricted_uart_peripherals
Does this pointer hast to be valid if `count = 0`?
It seems fair to me to have a NULL pointer there and simplify the code :)

2021-07-15 21:20 UTC, ithinuel approved these changes

2021-07-16 13:05 UTC, fkjagodzinski commented
Rebase done. I managed to reduce the number of commits down to 8! @MarceloSalazar , @ithinuel your reviews got cancelled by that force push, so I have to ask you to review/accept again. :wink:

2021-07-16 14:37 UTC, MarceloSalazar approved these changes

2021-07-19 10:25 UTC, ithinuel approved these changes

2021-07-19 10:25 UTC, merged