Enable uart tests
MCU-Driver-HAL/MCU-Driver-HAL pull request #37
Opened 2021-07-13 12:04 UTC by fkjagodzinski

This patch builds on top of #32 and has to wait for it to be merged. Until then, this will be marked as a _draft PR_.

- Enable `tests/mbed_hal_fpga_ci_test_shield/uart`.

2021-07-19 17:14 UTC, hugueskamba commented
Can you please also include this patch?

It helps with ensuring that devices which do not `DEVICE_SERIAL_FC` but do define `DEVICE_SERIAL` compile without error and reduced warnings.
[fpga_shield_uart.patch.txt](https://github.com/MCU-Driver-HAL/MCU-Driver-HAL/files/6842749/fpga_shield_uart.patch.txt)

2021-07-20 11:38 UTC, fkjagodzinski commented
Fixed the include directive for `DEVICE_SERIAL_FC=0` case and also the unused variable warning.

2021-07-21 08:47 UTC, ithinuel requested changes

2021-07-21 11:22 UTC, fkjagodzinski commented on CMakeLists.txt
> +add_subdirectory(examples/pwm EXCLUDE_FROM_ALL)
OK, removed the unrelated clean-up.

2021-07-21 11:24 UTC, fkjagodzinski commented
Commits rebased and squashed. This is ready for review and merge. :wink:

2021-07-21 14:27 UTC, ithinuel requested changes

2021-07-21 14:27 UTC, ithinuel commented on tests/mbed_hal_fpga_ci_test_shield/uart/main.cpp
> +        // Wait twice the time of one packet transfer for
why this change in behaviour when `us_ticker_read` is available?

2021-07-21 14:27 UTC, ithinuel commented on tests/mbed_hal_fpga_ci_test_shield/uart/main.cpp
> +    srand((unsigned) us_ticker_read());
This is deceptive. Init is fairly constant so this seed is not random.

2021-07-21 14:27 UTC, ithinuel commented on tests/mbed_hal_fpga_ci_test_shield/uart/uart_fpga_test.h
>  #if DEVICE_SERIAL
why isn't this occurrence removed as well?

2021-07-21 14:27 UTC, ithinuel commented on tools/fpga_ci_test_shield/include/fpga_ci_test_shield/test_utils.h
> +#if DEVICE_SERIAL
why are they splitted?

2021-07-21 14:27 UTC, ithinuel commented on hal/include/hal/static_pinmap.h
> +
can we not add them and remove the include for that c++ header?

2021-07-21 14:27 UTC, ithinuel commented on hal/CMakeLists.txt
> +        source/mbed_lp_ticker_api.c
why is this moved? it is not related to this PR.

2021-07-21 14:27 UTC, ithinuel commented on hal/CMakeLists.txt
> +        source/static_pinmap.cpp
why is this added?

2021-07-21 14:27 UTC, ithinuel commented on hal/CMakeLists.txt
> +        source/mbed_gpio.c
why is it moved?

2021-07-21 20:33 UTC, fkjagodzinski commented on tests/mbed_hal_fpga_ci_test_shield/uart/main.cpp
> +        // Wait twice the time of one packet transfer for
This is simpler. We only want to check if the char has been received by the test shield in a defined time window. Using `us_ticker_read()` also means ticks->time conversion. I don't like all this extra code here; `wait_us()` is sufficient. I'm also aware this means the test takes longer to complete, but I think we can disregard that.

2021-07-21 20:39 UTC, fkjagodzinski commented on tests/mbed_hal_fpga_ci_test_shield/uart/main.cpp
> +    srand((unsigned) us_ticker_read());
True; this as bad as what we had before. Anyway, any idea how to improve that?

2021-07-21 20:41 UTC, fkjagodzinski commented on tests/mbed_hal_fpga_ci_test_shield/uart/uart_fpga_test.h
>  #if DEVICE_SERIAL
Could you elaborate? I did not remove any `DEVICE_SERIAL`.

2021-07-21 20:45 UTC, fkjagodzinski commented on tools/fpga_ci_test_shield/include/fpga_ci_test_shield/test_utils.h
> +#if DEVICE_SERIAL
There are cases where `DEVICE_SERIAL` is defined and `DEVICE_SERIAL_FC` is not. The header has to be there also for these cases.

2021-07-21 20:47 UTC, fkjagodzinski commented on hal/include/hal/static_pinmap.h
> +
I don't follow. Which parts do you want removed?

2021-07-21 20:54 UTC, fkjagodzinski commented on hal/CMakeLists.txt
> +        source/mbed_gpio.c
I added an item to the list and then sorted the list. This is must have been in the wrong position and got sorted.

2021-07-21 20:55 UTC, fkjagodzinski commented on hal/CMakeLists.txt
> +        source/mbed_lp_ticker_api.c
This is an effect of sorting the list.

2021-07-21 20:58 UTC, fkjagodzinski commented on hal/CMakeLists.txt
> +        source/static_pinmap.cpp
The commits are squashed now and I don't see a description for that, I'll check the details. This is probably required by the main.cpp.

2021-07-21 21:19 UTC, fkjagodzinski commented on hal/CMakeLists.txt
> +        source/static_pinmap.cpp
Good catch! This change should be reverted; the test builds fine without `source/static_pinmap.cpp`. Will fix that.

2021-07-21 21:26 UTC, fkjagodzinski commented on hal/CMakeLists.txt
> +        source/static_pinmap.cpp
Fixed via f766fcd.

2021-07-22 09:36 UTC, ithinuel commented on hal/include/hal/static_pinmap.h
> +
line 34 to 59 :)

2021-07-22 09:40 UTC, ithinuel commented on tests/mbed_hal_fpga_ci_test_shield/uart/main.cpp
> +        // Wait twice the time of one packet transfer for
`wait_us` is deceptive. It hides this code and makes the requirement for the us_ticker.
The verbosity of the previous code isn't satisfying but it is better than `wait_us`.

`wait_us` may not use us_ticker on some platform which make this even more complex and is a pitfall we already encountered in the past weeks.

2021-07-22 09:42 UTC, ithinuel commented on tests/mbed_hal_fpga_ci_test_shield/uart/main.cpp
> +    srand((unsigned) us_ticker_read());
Not to use random if it is not random.
Define a constant and get rid of occurences of `rand` is the simplest path forward.

2021-07-22 09:44 UTC, ithinuel commented on tests/mbed_hal_fpga_ci_test_shield/uart/uart_fpga_test.h
>  #if DEVICE_SERIAL
I meat, with the other recent PR that did remove their related `DEVICE_*`.
If my understanding is correct, in the grand scheme of things, dependencies on peripherals shall be evaluated by CMake and not done in code with `#ifdef`s.

2021-07-22 11:18 UTC, fkjagodzinski commented on hal/include/hal/static_pinmap.h
> +
There are [test cases](https://github.com/MCU-Driver-HAL/MCU-Driver-HAL/blob/efab67e6bbe6120d2e0418f16698f21bbd1782dd/tests/mbed_hal_fpga_ci_test_shield/uart/main.cpp#L354) that require [`get_uart_pinmap()`](https://github.com/MCU-Driver-HAL/MCU-Driver-HAL/blob/efab67e6bbe6120d2e0418f16698f21bbd1782dd/tests/mbed_hal_fpga_ci_test_shield/uart/main.cpp#L142). This is why we need to `#include "hal/static_pinmap.h"`. This however, declares all it's functions as `MSTD_CONSTEXPR_FN_14` which is not available in our HAL repo. It is provided by the `cxxsupport` in the mbed-os world.

2021-07-22 11:23 UTC, fkjagodzinski commented on hal/include/hal/static_pinmap.h
> +
`serial_init_direct()` is still present in our HAL API so should be tested. Adding these defines seems to be the easiest fix for that.

2021-07-22 12:06 UTC, fkjagodzinski commented on tests/mbed_hal_fpga_ci_test_shield/uart/main.cpp
> +        // Wait twice the time of one packet transfer for
OK, I'll update that not to use `wait_us()`.

2021-07-22 13:55 UTC, fkjagodzinski commented on tests/mbed_hal_fpga_ci_test_shield/uart/main.cpp
> +        // Wait twice the time of one packet transfer for
Done, 8dc66d008dffd11a79e1d45ba4c74c4d783bcc6c.

2021-07-22 14:27 UTC, fkjagodzinski commented
Rebased and squashed the commits. This may be considered ready if we all agree to deal with the unresolved comments in the future. :slightly_smiling_face:

2021-07-22 14:46 UTC, ithinuel approved these changes

2021-07-22 14:50 UTC, MarceloSalazar approved these changes

2021-07-22 14:50 UTC, merged