Update testing section of porting guide
MCU-Driver-HAL/MCU-Driver-HAL pull request #53
Opened 2021-07-21 15:28 UTC by gpsimenos

### Description 
 

 This PR replaces the outdated testing section of the porting guide with a mostly-rewritten guide:
* Removed unnecessary references to Mbed
* Replaced Mbed examples and command lines with relevant MCU-Driver-HAL examples and command lines
* Removed references to automated testing at that does not apply yet to MCU-Driver-HAL
----------------------------------------------------------------------------------------------------------------
### Pull request type 

    [X] Patch update (Bug fix / Target update / Docs update / Test update / Refactor)
    [] Feature update (New feature / Functionality change / New API)
    [] Major update (Breaking change E.g. Return code change / API behaviour change)

----------------------------------------------------------------------------------------------------------------
### Test coverage 
 

[] Manual testing (and evidence provided)
[X] No additional tests required for this change (e.g documentation update)

2021-07-21 16:26 UTC, hugueskamba commented on docs/porting/porting_full_process/built_in_tests.md
> -1. Manually running the Mbed OS built-in tests.
Are these statements still true (minus the Mbed OS part)?

2021-07-21 16:26 UTC, hugueskamba commented on docs/porting/porting_full_process/built_in_tests.md
> +1. Go into the directory of the test for the module you want to test, e.g. `MCU-Driver-Arm/sdfx_arm/tests/mbed_hal/echo/`.
```suggestion
1. Go to the directory containing the CMake build instructions for the test application binary you would like to run.
```

2021-07-21 16:26 UTC, hugueskamba commented on docs/porting/porting_full_process/built_in_tests.md
> +2. Run `cmake -S . -B cmake_build` to generate the build system files.
```suggestion
1. Generate the build system files.
    ````
    cmake -S . -B cmake_build -D GREENTEA_CLIENT_STDIO=OFF -D MBED_TOOLCHAIN=<TOOLCHAIN> -D CMAKE_BUILD_TYPE=debug
    ````
```

2021-07-21 16:26 UTC, hugueskamba commented on docs/porting/porting_full_process/built_in_tests.md
> +3. Run `cmake --build cmake_build -j` to compile the test.
```suggestion
3. Compile the test.
    ````
    cmake --build cmake_build -j
    ````
```

2021-07-21 16:26 UTC, hugueskamba commented on docs/porting/porting_full_process/built_in_tests.md
> +You can use `mbedhtrun` with the following options to run a test:
```suggestion
Use `mbedhtrun` with the following options to run a test:
```

2021-07-21 16:26 UTC, hugueskamba commented on docs/porting/porting_full_process/built_in_tests.md
> +If your hardware doesn't have a DAPLINK interface, you can flash the test binary manually via other means, manually reset the hardware, omit the `-d <path/to/DAPLINK/mount/point>` option and pass the
```suggestion
If your hardware does not have a DAPLINK interface, you can program the test app binary via other means. After manually resetting the hardware, omit the `-d` and `-f` optional command line arguments and pass the `--skip-reset --skip-flashing` argument to `mbedhtrun`.
```

2021-07-21 16:26 UTC, hugueskamba commented on docs/porting/porting_full_process/built_in_tests.md
> +Example command line: `mbedhtrun -f ./sdfx_st/tests/mbed_hal/echo/cmake_build/sdfx-st-test-echo.bin -e ./MCU-Driver-HAL/tests/host_tests -d /Volumes/DIS_L4IOT -p /dev/tty.usbmodem145103:115200`
```suggestion
e.g
 ``
  mbedhtrun -f ./sdfx_st/tests/mbed_hal/echo/cmake_build/sdfx-st-test-echo.bin -e ./MCU-Driver-HAL/tests/host_tests -d /Volumes/DIS_L4IOT -p /dev/tty.usbmodem145103:115200
 ``
```

2021-07-21 16:26 UTC, hugueskamba commented on docs/porting/porting_full_process/built_in_tests.md
> +Example command line (without DAPLINK): `mbedhtrun -f ./sdfx_st/tests/mbed_hal/echo/cmake_build/sdfx-st-test-echo.bin -e ./MCU-Driver-HAL/tests/host_tests -p /dev/tty.usbmodem145103:115200 --skip-res
```suggestion
e.g
``
mbedhtrun -f ./sdfx_st/tests/mbed_hal/echo/cmake_build/sdfx-st-test-echo.bin -e ./MCU-Driver-HAL/tests/host_tests -p /dev/tty.usbmodem145103:115200 --skip-reset --skip-flashing
``
```

2021-07-21 16:26 UTC, hugueskamba commented on docs/porting/porting_full_process/built_in_tests.md
> +Greetea output for a test that ran successfully looks like this:
```suggestion
The Greentea output for a test that ran successfully would be similar to the following:
```

2021-07-21 16:26 UTC, hugueskamba commented on docs/porting/porting_full_process/built_in_tests.md
> -1. Flash the program with pyOCD (using the same configuration you used when you initially set up pyOCD).
This might still be possible.

2021-07-22 07:47 UTC, gpsimenos commented on docs/porting/porting_full_process/built_in_tests.md
> -1. Manually running the Mbed OS built-in tests.
No, I believe we don't have semi-automatic testing in MCU-Driver-HAL yet (e.g. running `mbed test` which would build and run all greentea tests for the connected targets).

2021-07-22 08:16 UTC, gpsimenos commented on docs/porting/porting_full_process/built_in_tests.md
> +2. Run `cmake -S . -B cmake_build` to generate the build system files.
MBED_TOOLCHAIN doesn't seem to be needed.

2021-07-22 09:50 UTC, MarceloSalazar commented on docs/porting/porting_full_process/built_in_tests.md
> -1. Manually running the Mbed OS built-in tests.
We have semi-automatic tests although I'm not fuzzy about this terminology. The instructions are ok IMO.

2021-07-22 09:59 UTC, MarceloSalazar commented on docs/porting/porting_full_process/built_in_tests.md
```suggestion
See [docs](../../docs/user/README.md) about tools setup.
```

2021-07-22 10:02 UTC, MarceloSalazar commented on docs/porting/porting_full_process/built_in_tests.md
> +MCU-Driver-ST % mbedhtrun -f ./sdfx_st/tests/mbed_hal/echo/cmake_build/sdfx-st-test-echo.bin -e ./MCU-Driver-HAL/tests/host_tests -d /Volumes/DIS_L4IOT -p /dev/tty.usbmodem145103:115200
Remove details on specific environment
```suggestion
mbedhtrun -f ./sdfx_st/tests/mbed_hal/echo/cmake_build/sdfx-st-test-echo.bin -e ./MCU-Driver-HAL/tests/host_tests -d /Volumes/DIS_L4IOT -p /dev/tty.usbmodem145103:115200
```

2021-07-22 10:06 UTC, MarceloSalazar commented on docs/porting/porting_full_process/built_in_tests.md
>  - Low power ticker.
I don't think we need LPticker. We consider usTicker sufficient.
```suggestion
```

2021-07-22 10:06 UTC, MarceloSalazar requested changes
Please make minor changes.

2021-07-22 10:08 UTC, MarceloSalazar commented on docs/porting/porting_full_process/built_in_tests.md
> -1. Flash the program with pyOCD (using the same configuration you used when you initially set up pyOCD).
Although it's possible, it's very specific. htrun handles the flash through mass storage.
I'm ok to remove this.

2021-07-22 10:39 UTC, MarceloSalazar commented on docs/porting/porting_full_process/built_in_tests.md
> +2. Run `cmake -S . -B cmake_build` to generate the build system files.
It's needed, according to the build scripts
https://github.com/MCU-Driver-HAL/MCU-Driver-ST/blob/main/sdfx_st/tests/build_all.sh#L40

2021-07-22 10:43 UTC, MarceloSalazar commented on docs/porting/porting_full_process/built_in_tests.md
> +If your hardware doesn't have a DAPLINK interface, you can flash the test binary manually via other means, manually reset the hardware, omit the `-d <path/to/DAPLINK/mount/point>` option and pass the
pending to review/update

2021-07-22 10:44 UTC, MarceloSalazar commented on docs/porting/porting_full_process/built_in_tests.md
> +Example command line: `mbedhtrun -f ./sdfx_st/tests/mbed_hal/echo/cmake_build/sdfx-st-test-echo.bin -e ./MCU-Driver-HAL/tests/host_tests -d /Volumes/DIS_L4IOT -p /dev/tty.usbmodem145103:115200`
pending to review/update

2021-07-22 10:45 UTC, MarceloSalazar commented on docs/porting/porting_full_process/built_in_tests.md
> +Example command line (without DAPLINK): `mbedhtrun -f ./sdfx_st/tests/mbed_hal/echo/cmake_build/sdfx-st-test-echo.bin -e ./MCU-Driver-HAL/tests/host_tests -p /dev/tty.usbmodem145103:115200 --skip-res
pending to review/update

2021-07-22 10:45 UTC, MarceloSalazar commented on docs/porting/porting_full_process/built_in_tests.md
> +Greetea output for a test that ran successfully looks like this:
pending to review/update

2021-07-22 11:27 UTC, gpsimenos commented on docs/porting/porting_full_process/built_in_tests.md
> +2. Run `cmake -S . -B cmake_build` to generate the build system files.
If not provided, it defaults to GCC_ARM here https://github.com/MCU-Driver-HAL/MCU-Driver-HAL/blob/efab67e6bbe6120d2e0418f16698f21bbd1782dd/CMakeLists.txt#L18

You only need to pass it if you want to use a different toolchain.

Also regarding GREENTEA_CLIENT_STDIO, I've had another look and I believe it's not needed. It's OFF by default anyways and it seems we're always using greentea-custom_io in MCU-Driver-HAL so setting GREENTEA_CLIENT_STDIO=ON would just break all our tests.

2021-07-22 11:28 UTC, gpsimenos commented on docs/porting/porting_full_process/built_in_tests.md
> +If your hardware doesn't have a DAPLINK interface, you can flash the test binary manually via other means, manually reset the hardware, omit the `-d <path/to/DAPLINK/mount/point>` option and pass the
I made some changes to this part, I think it looks ok now.

2021-07-22 11:29 UTC, gpsimenos commented on docs/porting/porting_full_process/built_in_tests.md
> +Example command line: `mbedhtrun -f ./sdfx_st/tests/mbed_hal/echo/cmake_build/sdfx-st-test-echo.bin -e ./MCU-Driver-HAL/tests/host_tests -d /Volumes/DIS_L4IOT -p /dev/tty.usbmodem145103:115200`
I think it's ok as is

2021-07-22 11:29 UTC, gpsimenos commented on docs/porting/porting_full_process/built_in_tests.md
> +Example command line (without DAPLINK): `mbedhtrun -f ./sdfx_st/tests/mbed_hal/echo/cmake_build/sdfx-st-test-echo.bin -e ./MCU-Driver-HAL/tests/host_tests -p /dev/tty.usbmodem145103:115200 --skip-res
I think it's ok as is

2021-07-22 11:29 UTC, gpsimenos commented on docs/porting/porting_full_process/built_in_tests.md
> +Greetea output for a test that ran successfully looks like this:
I think it's ok as is

2021-07-22 11:30 UTC, gpsimenos commented on docs/porting/porting_full_process/built_in_tests.md
> +3. Run `cmake --build cmake_build -j` to compile the test.
Applied

2021-07-22 11:30 UTC, gpsimenos commented on docs/porting/porting_full_process/built_in_tests.md
> +1. Go into the directory of the test for the module you want to test, e.g. `MCU-Driver-Arm/sdfx_arm/tests/mbed_hal/echo/`.
Made some changes to this

2021-07-22 14:26 UTC, MarceloSalazar commented on docs/porting/porting_full_process/built_in_tests.md
> +2. Run `cmake -S . -B cmake_build` to generate the build system files.
I like simpler instructions and I'm glad to hear that we can get rid of `GREENTEA_CLIENT_STDIO`.

We need to support two toolchains (GCC_ARM and ARM) but I see you already added instructions on how users can do it.

2021-07-22 14:27 UTC, MarceloSalazar approved these changes

2021-07-22 14:51 UTC, MarceloSalazar commented
@gpsimenos please fix your DCO and squash.

2021-07-22 15:11 UTC, ithinuel requested changes

2021-07-22 15:11 UTC, ithinuel commented on docs/porting/porting_full_process/built_in_tests.md
> +### Compiling tests
This section and the following (running the tests) are platform specific (even if they share a common theme).
That IMHO do not belong here.

The expected output, to give a rough idea of what to expect when running the tests, is fine but the first line  (with the command) needs to be removed.

2021-07-22 15:15 UTC, MarceloSalazar commented on docs/porting/porting_full_process/built_in_tests.md
> +### Compiling tests
I assume you mean `Example command line` in lines 46-49. 
I tend to agree and prefer this to be removed. There is another example below.

2021-07-25 22:03 UTC, ithinuel commented on docs/porting/porting_full_process/built_in_tests.md
> +### Compiling tests
I mean moving lines  25-57 to the relevant SiP repo and removing line 63-64 without necessarily moving them to somewhere else.

2021-07-27 11:31 UTC, gpsimenos commented on docs/porting/porting_full_process/built_in_tests.md
> +### Compiling tests
Aside from the paths in the examples, the rest isn't platform specific, no? I we remove everything regarding compiling and running tests there won't be much point having this file/guide at all.

2021-07-27 16:50 UTC, MarceloSalazar commented on docs/porting/porting_full_process/built_in_tests.md
> +1. Go to the directory containing the `CMakeLists.txt` file of the test you want to run, e.g. `MCU-Driver-Arm/sdfx_arm/tests/mbed_hal/echo/`.
```suggestion
1. Go to the directory containing the `CMakeLists.txt` file of the test you want to run.
```

2021-07-27 16:51 UTC, MarceloSalazar commented on docs/porting/porting_full_process/built_in_tests.md
> +mbedhtrun -f ./sdfx_st/tests/mbed_hal/echo/cmake_build/sdfx-st-test-echo.bin -e ./MCU-Driver-HAL/tests/host_tests -d /Volumes/DIS_L4IOT -p /dev/tty.usbmodem145103:115200
```suggestion
mbedhtrun -f ./tests/mbed_hal/echo/cmake_build/....bin -e ./MCU-Driver-HAL/tests/host_tests -d /Volumes/XXX -p /dev/tty.usbmodem145103:115200
```

2021-07-27 16:51 UTC, MarceloSalazar commented on docs/porting/porting_full_process/built_in_tests.md
> +mbedhtrun -f ./sdfx_st/tests/mbed_hal/echo/cmake_build/sdfx-st-test-echo.bin -e ./MCU-Driver-HAL/tests/host_tests -d /Volumes/DIS_L4IOT -p /dev/tty.usbmodem145103:115200
```suggestion
mbedhtrun -f ./tests/mbed_hal/echo/cmake_build/s.....bin -e ./MCU-Driver-HAL/tests/host_tests -d /Volumes/XXX -p /dev/tty.usbmodem145103:115200
```

2021-07-27 16:58 UTC, MarceloSalazar commented on docs/porting/porting_full_process/built_in_tests.md
> +mbedhtrun -e ./MCU-Driver-HAL/tests/host_tests -p /dev/tty.usbmodem145103:115200 --skip-reset --skip-flashing
```suggestion
mbedhtrun -e ./MCU-Driver-HAL/tests/host_tests -p /dev/ttyXXX:115200 --skip-reset --skip-flashing
```

2021-07-27 17:03 UTC, MarceloSalazar commented on docs/porting/porting_full_process/built_in_tests.md
> +   The default toolchain is GCC_ARM. You can use a different toolchain by passing `-D MBED_TOOLCHAIN=<TOOLCHAIN>`. If you need to debug the binary, build with `-D CMAKE_BUILD_TYPE=debug`.
```suggestion
   The default toolchain is GCC_ARM. You can use a different toolchain by passing `-D MBED_TOOLCHAIN=<TOOLCHAIN>`. The default CMake build type option is `develop`, best for debugging.
```

2021-07-27 17:04 UTC, MarceloSalazar requested changes
Please remove platform specific code.

2021-07-28 07:13 UTC, MarceloSalazar commented on docs/porting/porting_full_process/built_in_tests.md
> +### Compiling tests
See suggestions on minor things to tweak.

2021-07-29 10:22 UTC, ithinuel approved these changes

2021-07-29 12:51 UTC, MarceloSalazar approved these changes

2021-07-29 12:51 UTC, merged