cmake: rename MBED_TOOLCHAIN to COMPILER
MCU-Driver-HAL/MCU-Driver-HAL pull request #7
Opened 2021-06-24 10:38 UTC by galak

Signed-off-by: Kumar Gala <kumar.gala@linaro.org>

2021-06-24 10:46 UTC, pfalcon commented
Is `COMPILER` a good term for this? Maybe `TOOLCHAIN` would be better after all (it's not e.g. a compiler executable, it's toolchain type).

2021-06-24 10:46 UTC, MarceloSalazar commented
Thanks for the proposal. 

I don't think we're ready to make this change right now.
The configuration files an macros are automatically generated (see [cmake](https://github.com/MCU-Driver-HAL/MCU-Driver-HAL/blob/0.1.0/docs/porting/cmake.md) doc). This is something we need to evolve.

2021-06-24 11:11 UTC, galak commented
> Is `COMPILER` a good term for this? Maybe `TOOLCHAIN` would be better after all (it's not e.g. a compiler executable, it's toolchain type).

COMPILER is what TF-M and I think FreeRTOS are using.

2021-06-24 11:14 UTC, galak commented
> I don't think we're ready to make this change right now.
> The configuration files an macros are automatically generated (see [cmake](https://github.com/MCU-Driver-HAL/MCU-Driver-HAL/blob/0.1.0/docs/porting/cmake.md) doc). This is something we need to evolve.

Why would we need to update those files again at this point?  This change is the start of evolving away.

2021-06-24 12:32 UTC, 0xc0170 commented on CMakeLists.txt
> +    if(NOT DEFINED COMPILER OR "${COMPILER}" STREQUAL "GCC_ARM")
We might just use what CMake provides as default, do not need to invent our own variables. CMake provides variables like `CMAKE_C_COMPILER_ID`  that could be checked if its ARMClang or Gcc Arm or any other.

We could just use `CMAKE_<LANG>_COMPILER_ID` instead of MBED_TOOLCHAIN as a start.

I might misunderstood the tree hierarchy but this repository is one of many, isn't it? I would expect to have just simple CMakelists.txt file describing this library (we should refactor this and bring some of the functionality elsewhere - there is plenty of common functionality in this file - setting a toolchain, post hooks etc).

2021-06-25 09:32 UTC, hugueskamba requested changes
Toolchain refers to all the tools used to build the artefacts. Compiler is inaccurate as we refers to more than just the compiler were that CMake variable is used.
Also as a more general cleanup of the Mbed namespace is needed, I would not start modifying individual references of Mbed as is done here unless there is something blocking the progression of the work.
Is there something blocking?
Note also that the CMake variable is generated from the tools we currently rely on. We would need to assign the generated value to the new variable (as and when it is appropriate to start renaming).

2021-06-25 12:52 UTC, galak commented
> Toolchain refers to all the tools used to build the artefacts. Compiler is inaccurate as we refers to more than just the compiler were that CMake variable is used.
> Also as a more general cleanup of the Mbed namespace is needed, I would not start modifying individual references of Mbed as is done here unless there is something blocking the progression of the work.
> Is there something blocking?
> Note also that the CMake variable is generated from the tools we currently rely on. We would need to assign the generated value to the new variable (as and when it is appropriate to start renaming).

This is the one variable is the most user visible case.

Have to start somewhere and wanted to also see what how the process of submission and acceptance goes to identify what we need to address in the process.

I don't have any particular concern about it being TOOLCHAIN or COMPILER.  I agree with your point about TOOLCHAIN, however COMPILER was used by TF-M and AWS FreeRTOS.  I know Zephyr uses ZEPHYR_TOOLCHAIN_VARIANT and Azure seems to use THREADX_TOOLCHAIN.  CMake itself a form of 'COMPILER' as well (CMAKE_${lang}_COMPILER_ID).

2021-07-01 16:15 UTC, evedon commented on CMakeLists.txt
> +    if(NOT DEFINED COMPILER OR "${COMPILER}" STREQUAL "GCC_ARM")
I like your suggestion to use `CMAKE_<LANG>_COMPILER_ID`

2021-07-13 06:42 UTC, closed without merging

2021-07-13 07:09 UTC, 0xc0170 commented
@galak As indicated in #26 , we cleaned up the history. As result, this pull request was automatically closed by github due to different base (diverged).

Please create a tracking issue for CMake clean up where we can estimate what we should do step by step (one of them will be proper toolchain file with all its variables).